### ISSUE TITLE
W11k-flash with Angular 4 

### ISSUE THREAD

**Issue by aryanisml** [w11k/w11k-flash#5]
1. W11k-flash support angular 4 ?
2. Any example or plunker to show the use of W11k-flash with angular 4

**Comment by pburgmer** [comment]
Hi,

w11k-flash only supports AngularJS. It does not support Angular. And unfortunately there are no plans to migrate it to Angular.

Kind regards
Philipp

**Comment by aryanisml** [comment]
Please correct me, currently using AngularJS 1.6 and w11k-flash have good support for it.
Is there is no support of w11k-flash with AngularJS 4 ?

**Comment by pburgmer** [comment]
Please keep in mind: AngularJS and Angular are different frameworks. Angular 2 is a complete rewrite and incompatible with AngularJS 1.x. Angular 4 (and now Angular 5) are updates for Angular 2.
To support Angular we have to rewrite w11k-flash. Unfortunately we don't have time to do that.
